package com.divanov.mathwebservice.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2023-02-19T23:32:06.572+03:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://math.ws.divanov", name = "MathPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MathPort {

    @WebMethod
    @WebResult(name = "quadraticEducationResponse", targetNamespace = "http://math.ws.divanov", partName = "quadraticEducationResponse")
    public QuadraticEducationResponse quadraticEducation(

        @WebParam(partName = "quadraticEducationRequest", name = "quadraticEducationRequest", targetNamespace = "http://math.ws.divanov")
        QuadraticEducationRequest quadraticEducationRequest
    ) throws QuadraticEducationFault_Exception;
}
