
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.divanov.mathwebservice.dto;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2023-02-21T20:51:50.460+03:00
 * Generated source version: 3.5.3
 *
 */

@javax.jws.WebService(
                      serviceName = "MathService",
                      portName = "MathPortSoap11",
                      targetNamespace = "http://math.ws.divanov",
                      wsdlLocation = "http://localhost:8080/services/MathService.wsdl",
                      endpointInterface = "com.divanov.mathwebservice.dto.MathPort")

public class MathPortSoap11Impl implements MathPort {

    private static final Logger LOG = Logger.getLogger(MathPortSoap11Impl.class.getName());

    /* (non-Javadoc)
     * @see com.divanov.mathwebservice.dto.MathPort#quadraticEducation(com.divanov.mathwebservice.dto.QuadraticEducationRequest quadraticEducationRequest)*
     */
    public com.divanov.mathwebservice.dto.QuadraticEducationResponse quadraticEducation(QuadraticEducationRequest quadraticEducationRequest) throws QuadraticEducationFault_Exception   {
        LOG.info("Executing operation quadraticEducation");
        System.out.println(quadraticEducationRequest);
        try {
            com.divanov.mathwebservice.dto.QuadraticEducationResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new QuadraticEducationFault_Exception("quadraticEducationFault...");
    }

}
