version: "3.9"
services:
  rest_service:
    build: ./RESTClient
    container_name: rest_service
    ports:
      - "9090:9090"
    depends_on:
      - soap_service
    networks:
      - proxynet
  soap_service:
    build: ./SoapService
    container_name: soap_service
    ports:
      - "8080:8080"
    networks:
      - proxynet 
    restart: always
networks:
  proxynet:
    name: custom_network