
package com.divanov.mathwebservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MathServiceEndpoint", targetNamespace = "http://math.ws.divanov")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MathServiceEndpoint {


    /**
     * 
     * @param quadraticEducationRequest
     * @return
     *     returns com.divanov.mathwebservice.client.QuadraticEducationResponse
     * @throws QuadraticEducationFault_Exception
     */
    @WebMethod(operationName = "QuadraticEducation")
    @WebResult(name = "QuadraticEducationResponse", targetNamespace = "http://math.ws.divanov", partName = "QuadraticEducationResponse")
    public QuadraticEducationResponse quadraticEducation(
        @WebParam(name = "QuadraticEducationRequest", targetNamespace = "http://math.ws.divanov", partName = "QuadraticEducationRequest")
        QuadraticEducationRequest quadraticEducationRequest)
        throws QuadraticEducationFault_Exception
    ;

}
