
package com.divanov.mathwebservice.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "QuadraticEducationFault", targetNamespace = "http://math.ws.divanov")
public class QuadraticEducationFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private QuadraticEducationFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public QuadraticEducationFault_Exception(String message, QuadraticEducationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public QuadraticEducationFault_Exception(String message, QuadraticEducationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.divanov.mathwebservice.client.QuadraticEducationFault
     */
    public QuadraticEducationFault getFaultInfo() {
        return faultInfo;
    }

}
