//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.15 at 12:23:12 PM MSK 
//


package com.divanov.MathWebService.divanov.ws.math;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateGetSolutionQuadraticEducation complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreateGetSolutionQuadraticEducation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="educationParams" type="{http://math.ws.divanov}EducationParams" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateGetSolutionQuadraticEducation", propOrder = {
        "educationParams"
})
public class CreateGetSolutionQuadraticEducation {

    protected EducationParams educationParams;

    /**
     * Gets the value of the educationParams property.
     *
     * @return possible object is
     * {@link EducationParams }
     */
    public EducationParams getEducationParams() {
        return educationParams;
    }

    /**
     * Sets the value of the educationParams property.
     *
     * @param value allowed object is
     *              {@link EducationParams }
     */
    public void setEducationParams(EducationParams value) {
        this.educationParams = value;
    }

}
