//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.15 at 12:23:12 PM MSK 
//


package com.divanov.MathWebService.divanov.ws.math;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EducationParams complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EducationParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="a" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="b" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="c" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EducationParams", propOrder = {
        "a",
        "b",
        "c"
})
public class EducationParams {

    protected double a;
    protected double b;
    protected double c;

    /**
     * Gets the value of the a property.
     */
    public double getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     */
    public void setA(double value) {
        this.a = value;
    }

    /**
     * Gets the value of the b property.
     */
    public double getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     */
    public void setB(double value) {
        this.b = value;
    }

    /**
     * Gets the value of the c property.
     */
    public double getC() {
        return c;
    }

    /**
     * Sets the value of the c property.
     */
    public void setC(double value) {
        this.c = value;
    }

}
