//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.17 at 10:44:24 PM MSK 
//


package com.divanov.MathWebService.divanov.ws.math;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the divanov.ws.math package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: divanov.ws.math
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateGetSolutionQuadraticEducationRequest }
     */
    public CreateGetSolutionQuadraticEducationRequest createCreateGetSolutionQuadraticEducationRequest() {
        return new CreateGetSolutionQuadraticEducationRequest();
    }

    /**
     * Create an instance of {@link CreateResponse }
     */
    public CreateResponse createCreateResponse() {
        return new CreateResponse();
    }

}
