package com.divanov.mathwebservice.client;

<<<<<<< HEAD
import com.divanov.mathwebservice.generated.*;
import org.apache.cxf.binding.soap.SoapFault;
=======
>>>>>>> 6cd713248a87e914ee87c21dae6e24827b296e01
import org.springframework.beans.factory.annotation.Autowired;

import javax.jws.WebService;
import javax.wsdl.WSDLException;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2023-02-09T23:06:39.264+03:00
 * Generated source version: 3.5.3
 */

@WebService(
        serviceName = "MathService",
        portName = "MathPortSoap11",
        targetNamespace = "http://math.ws.divanov",
        wsdlLocation = "http://localhost:8080/services/MathService.wsdl",
        endpointInterface = "com.divanov.mathwebservice.dto.MathPort")

public class MathPortSoap11Impl implements MathPort {

//    private final MathService service;
//
//    @Autowired
//    public MathPortSoap11Impl(MathService service) {
//        this.service = service;
//    }
<<<<<<< HEAD

    private final MathService service;

    @Autowired
    public MathPortSoap11Impl(MathService service) {
        this.service = service;
    }

    public MathService getService() {
        return service;
    }

    @Override
    public QuadraticEducationResponse quadraticEducation(QuadraticEducationRequest request) throws QuadraticEducationFault_Exception {
        QuadraticEducationResponse response = null;

        try {
            response = getService().getMathPortSoap11().quadraticEducation(request);
        } catch (QuadraticEducationFault_Exception ex) {
            System.err.println(ex.getMessage());
//            System.err.println(ex.getFaultInfo().getFormula());
//            System.err.println(ex.getFaultInfo().getD());
//        } catch (Exception exception) {
//            System.err.println(exception.getMessage());
//        }
        }
        return response;
    }
=======
//
//    public MathService getService() {
//        return service;
//    }
//
//    @Override
//    public QuadraticEducationResponse quadraticEducation(QuadraticEducationRequest request) throws QuadraticEducationFault_Exception {
//        QuadraticEducationResponse response = null;
//
//        try {
//            response = getService().getMathPortSoap11().quadraticEducation(request);
//        } catch (QuadraticEducationFault_Exception ex) {
//            System.err.println(ex.getMessage());
//        }
//        return response;
//    }
>>>>>>> 6cd713248a87e914ee87c21dae6e24827b296e01
}
