package com.divanov.mathwebservice.client;

<<<<<<< HEAD
import com.divanov.mathwebservice.generated.*;
=======
import com.divanov.mathwebservice.dto.*;
>>>>>>> fc3d050d9d5a7fa00c535335ff69abfa8e297c78
import org.apache.cxf.binding.soap.SoapFault;
import org.springframework.beans.factory.annotation.Autowired;

import javax.jws.WebService;
<<<<<<< HEAD
import javax.wsdl.WSDLException;
=======
>>>>>>> fc3d050d9d5a7fa00c535335ff69abfa8e297c78

/**
 * This class was generated by Apache CXF 3.5.3
 * 2023-02-09T23:06:39.264+03:00
 * Generated source version: 3.5.3
 */

@WebService(
        serviceName = "MathService",
        portName = "MathPortSoap11",
        targetNamespace = "http://math.ws.divanov",
        wsdlLocation = "http://localhost:8080/services/MathService.wsdl",
        endpointInterface = "com.divanov.mathwebservice.dto.MathPort")

public class MathPortSoap11Impl implements MathPort {
//    @Override
//    public QuadraticEducationResponse quadraticEducation(QuadraticEducationRequest quadraticEducationRequest) {
//        QuadraticEducationResponse response = new QuadraticEducationResponse();
//
//        try {
//            response = (QuadraticEducationResponse) getWebServiceTemplate().marshalSendAndReceive(quadraticEducationRequest);
//        } catch (SoapFaultClientException e) {
//            System.err.println(e.getSoapFault());
//        }
//        return response;
//    }

    private final MathService service;

    @Autowired
    public MathPortSoap11Impl(MathService service) {
        this.service = service;
    }

    public MathService getService() {
        return service;
    }

    @Override
    public QuadraticEducationResponse quadraticEducation(QuadraticEducationRequest request) throws QuadraticEducationFault_Exception {
<<<<<<< HEAD
        QuadraticEducationResponse response = null;

        try {
            response = getService().getMathPortSoap11().quadraticEducation(request);
        } catch (QuadraticEducationFault_Exception ex) {
            System.err.println(ex.getMessage());
=======
        QuadraticEducationResponse response = new QuadraticEducationResponse();

//        try {
            response = getService().getMathPortSoap11().quadraticEducation(request);
//        } catch (QuadraticEducationFault_Exception ex) {
//            System.err.println(ex.getMessage());
>>>>>>> fc3d050d9d5a7fa00c535335ff69abfa8e297c78
//            System.err.println(ex.getFaultInfo().getFormula());
//            System.err.println(ex.getFaultInfo().getD());
//        } catch (Exception exception) {
//            System.err.println(exception.getMessage());
//        }
<<<<<<< HEAD
        }
        return response;
    }
=======
        return response;
    }


>>>>>>> fc3d050d9d5a7fa00c535335ff69abfa8e297c78
}
