
package com.divanov.mathwebservice.dto;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-12-28T21:58:29.766+03:00
 * Generated source version: 3.5.3
 *
 */

public class MathPort_MathPortSoap11_Server{

    protected MathPort_MathPortSoap11_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MathPortSoap11Impl();
        String address = "http://localhost:8080/services/MathServiceEndpoint";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new MathPort_MathPortSoap11_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
